title: "[General] "
labels:
  - "General Introduction"
body:
  - type: markdown
    attributes:
      value: |
        # 📝 Daily Scrum Report

        아래에 각 항목당 구체적으로 작성해 주세요.

        ---
  - type: textarea
    id: yesterday-work
    attributes:
      label: ✅ 다시 보기
      description: "이전 작업의 리뷰를 작성해 주세요."
      placeholder: |
        - 이전 회의의 주요 토픽 중 재 논의가 필요한 부분
    validations:
      required: true
  - type: textarea
    id: today-plan
    attributes:
      label: 🚀 프리뷰
      description: "앞으로 진행될 사항에 대한 의견을 작성해 주세요."
      placeholder: |
        - 토픽 및 토픽 제안자 작성
    validations:
      required: true
  - type: textarea
    id: blockers-review
    attributes:
      label: 🧷 계획 수정 사항 점검
      description: "작업 진행 중 수정이 필요한 경우 작성해 주세요."
      placeholder: |
        - 예: 토픽 및 토픽 제안자 작성
    validations:
      required: false
  - type: textarea
    id: blockers
    attributes:
      label: ⚠️ 현재 겪고 있는 문제
      description: "작업 진행 중 직면한 문제점이나 도움이 필요한 사항을 작성해주세요."
      placeholder: |
        - 예: API 오류 해결 필요
        - 예: 디자인 팀의 추가 자료 필요
    validations:
      required: false
  - type: textarea
    id: additional-checks
    attributes:
      label: ☂ 기타 점검사항
      description: "특이사항이나 점검 사항을 작성해 주세요."
      placeholder: |
        - 예: 팀원의 건강 상태
        - 예: 특이사항
    validations:
      required: false
  - type: checkboxes
    id: team-alignment
    attributes:
      label: 🌟 팀 정렬 확인
      options:
        - label: 오늘의 목표를 명확히 이해함
        - label: 지원이 필요한 팀원 있음
        - label: 모든 준비 완료
  - type: markdown
    attributes:
      value: |
        ## 📌 추가 참고 사항
        - 필요한 경우 댓글로 추가 정보를 공유해주세요.
