title: "[General] "
labels: ["General Introduction"]
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 새로운 아이디어 제안

        아이디어를 구체적으로 작성해주세요. 다음 항목을 포함하면 좋습니다:
        - 아이디어의 주요 목표
        - 해결하고자 하는 문제
        - 예상되는 결과나 이점

        ### 아래의 텍스트 필드를 채워주세요.
  - type: input
    id: idea-title
    attributes:
      label: 아이디어 제목
      description: "아이디어의 간략한 제목을 작성해주세요."
      placeholder: "예: 사용자 대시보드 개선"
    validations:
      required: true
  - type: textarea
    id: idea-details
    attributes:
      label: 아이디어 세부 사항
      description: "아이디어에 대한 자세한 설명을 작성해주세요."
      placeholder: |
        - 이 아이디어는 어떤 문제를 해결하나요?
        - 이 아이디어가 프로젝트에 어떤 가치를 더할 수 있나요?
        - 구현을 위해 필요한 자원 또는 단계는 무엇인가요?
    validations:
      required: true
  - type: dropdown
    id: idea-priority
    attributes:
      label: 아이디어의 우선순위
      description: "이 아이디어의 우선순위를 선택해주세요."
      options:
        - 낮음
        - 보통
        - 높음
    validations:
      required: true
  - type: checkboxes
    id: impacted-areas
    attributes:
      label: 이 아이디어가 영향을 미칠 수 있는 프로젝트 영역
      options:
        - label: 사용자 경험 (UX)
        - label: 기능 추가
        - label: 성능 개선
        - label: 버그 수정
  - type: markdown
    attributes:
      value: |
        ## 추가 자료 📎
        - 관련 문서, 스크린샷, 또는 참고 링크가 있다면 댓글로 첨부해주세요!
