title: "[General] "
labels: ["General Introduction"]
body:
  - type: markdown
    attributes:
      value: |
        This is text that will show up in the template!
  - type: textarea
    id: improvements_1
    attributes:
      label: 🔴 중요 공지사항 🔴
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: improvements_2
    attributes:
      label: 🔵 이전 공지사항 🔵
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: dropdown
    id: download
    attributes:
      label: "Which area of this project could be most improved?"
      options:
        - Documentation
        - Pull request review time
        - Bug fix time
        - Release cadence
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: ☑ 확인 결과 체크 ☑
      options:
        - label: 김규남
          required: true
        - label: 김남규
        - label: 윤이정
        - label: 이승현
