title: "[General] "
labels:
  - notice
  - pinned
title: "[Notice] "
body:
  - type: textarea
    id: announcement_details
    attributes:
      label: "공지 내용"
      description: "중요 공지 사항의 세부 내용을 작성하세요."
      placeholder: "예: 프로젝트 업데이트 일정, 주요 변경 사항"
      value: ""
  - type: markdown
    attributes:
      value: |
        ### 참고 사항
        - 공지에 대한 질문은 댓글로 남겨주세요.
        - 추가 자료가 있으면 링크를 첨부하세요.
